### ISSUE TITLE
How is IoC container better?

### ISSUE THREAD

**Issue by onmyway133** [ilyapuchka/ViewControllerThinning#1]
Hi, I really enjoy your series of View Controller thinning with IoC container. One thing that I wonder is how is IoC container better?

Like https://github.com/ilyapuchka/ViewControllerThinning/blob/typhoon/ViewControllerThinning/System/UIComponents.swift

Assume I have a class called `UIMaker`

```
class UIMaker {
    func authViewController() -> ViewController { ... }
    func authFormBehaviour() -> FormBehaviour { ... }
    func shakeAnimaton(view: UIView) -> ShakeAnimation { ... }
    func networkComponents() -> NetworkComponents { ... }
}
```

Then I can make things, config theirs properties. I see that it does the same as Typhoon, except it can't override properties like `def.injectProperty("nibName", with: "AuthView")`. 

Can you explain more about this? Many thanks

**Comment by ilyapuchka** [comment]
In general Dependency Injection is just an implementation of Inversion of Control Principle. It's a pattern. Besides DI there are few other patterns that you can use to achieve [IoC](https://en.wikipedia.org/wiki/Inversion_of_control). You can use DI without any containers. Instead of containers you can use your own factory classes. The main profit of IoC containers as I see it is automation and standardisation of the way how you define and resolve your dependencies, automatic dependencies resolution, managing components scope and lifecycle and providing well defined single point of setup. Speaking of Typhoon it also let you define a graph of assemblies, built of different layers of components. Sometimes it's a matter of taste or habit to do everything of that manually or to use ready-to-go solutions. Read "Your dependency injection options" section at [typhoonframework.org](http://typhoonframework.org)

**Comment by onmyway133** [comment]
@ilyapuchka thanks for your prompt reply. I got it. 

Speaking of IoC container, you have to setup components somewhere. Are there anytime you have a massive components ?
